---
title: "Overview on datasets for RT Prediction"
author: "Eva-Maria Harrieder, Michael Witting"
date: "17 1 2020"
output: pdf_document
params:
  data:  
    input: file  
    label: 'Input dataset:'  
    value: E:/Databases/RT_Pred/raw/datasets.xlsx
  folder: E:/Databases/RT_Pred
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Overview on datasets used for RT Prediction

## Introduction

Metabolite identification represents

## Scope

This is a report on `r params$data`

\newpage

## Reading the overview data

```{r libraries, echo = FALSE, message=FALSE}

# load all required libraries
library(tidyverse)
library(readxl)
library(knitr)
```

```{r, echo = FALSE}
rt_data_set_overview <- read_excel(paste0(params$folder, "/raw/datasets.xlsx"))

knitr::kable(rt_data_set_overview)
```


## overview on dataset

How many datasets have been described for the individual methods.

```{r, fig.cap="Test", echo=FALSE}
rt_data_set_methodcount <- rt_data_set_overview %>% count(separation.method)
ggplot(rt_data_set_methodcount, aes(x = separation.method, y = n)) +
  geom_bar(stat = "identity") +
  theme_bw()
```


## Individual datasets

\newpage

```{r, echo = FALSE, message = FALSE}
rt_data_sets <- list.dirs(paste0(params$folder, "/raw"), recursive = TRUE)

out = NULL

for(i in 2:length(rt_data_sets)) {
  
  # load Excel file with the actual RT data
  xlsx_file <- list.files(rt_data_sets[i], pattern = ".xlsx$", full.names = TRUE)
  rt_data <- read_excel(xlsx_file[1], sheet = "rt_data")
  
  # load all the metadata
  meta_data <- read_excel(xlsx_file[1], sheet = "meta_data")
  
  out <- c(out, knit_child('report_dataset.Rmd', quiet = TRUE))

}
```


```{r, echo=FALSE, results="asis"}
cat(paste(out, collapse = '\n'))
```