name: Fingerprints computation

on:
  workflow_dispatch

jobs:
  compute_fingerprints:
    name: Compute fingerprints for all available processed data sets
    # NOTE: on windows as computing of descriptors has a bug on linux right now
    runs-on: windows-2019
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # needed for pulling R packages from github

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
         lfs: true

    - name: Get all datasets
      id: filesfolders
      shell: bash {0}
      run: echo "files=$(ls -F processed_data/ | grep '/' | cut -d'/' -f1 | tr '\n' ' ')" >> $GITHUB_OUTPUT

    - name: List all added files
      shell: bash {0}
      run: |
        for f in ${{ steps.filesfolders.outputs.files }}; do
          ls -lh processed_data/$f
        done

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Set java version
      run: echo ("JAVA_HOME=" + $Env:JAVA_HOME_13_X64) >> $env:GITHUB_ENV

    - name: Install R packages
      run: Rscript scripts/R_ci/dependencies.R

    - name: Compounds fingerprints
      run: Rscript scripts/R_ci/04_compounds_fingerprints.R ${{ steps.filesfolders.outputs.files }}

    - name: Commit preprocessing
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        # Use LFS storage of main repository: no push access to fork LFS storage
        git config lfs.url 'https://github.com/michaelwitting/RtPredTrainingData.git/info/lfs'
        git add processed_data
        git commit -m "Fingerprints computation" -m "${{ steps.filesfolders.outputs.files }}"
        git lfs push origin HEAD # first push LFS, otherwise failure because of lfs.url
        git push origin HEAD

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
