name: Prepare R environment

on:
  workflow_dispatch

jobs:
  prepare_renv:
    name: Prepare R environment
    # NOTE: on windows as computing of descriptors has a bug on linux right now
    runs-on: windows-2019
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # needed for pulling R packages from github

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         ref: ${{ github.head_ref }}
         lfs: true

    - name: Set java version
      run: echo ("JAVA_HOME=" + $Env:JAVA_HOME_13_X64) >> $env:GITHUB_ENV

    - name: Set RENV_PATHS_ROOT
      shell: bash
      run: |
        echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Restore Renv package cache
      uses: actions/cache@v3
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Init renv
      shell: Rscript {0}
      run: |
        install.packages("renv")
        renv::init()
        renv::activate()

    - name: Install R dependencies
      run: Rscript scripts/R_ci/dependencies.R

    - name: Snapshot renv
      shell: Rscript {0}
      run: |
        renv::snapshot()

    - name: Commit
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        # Use LFS storage of main repository: no push access to fork LFS storage
        git config lfs.url 'https://github.com/michaelwitting/RepoRT.git/info/lfs'
        git add renv.lock renv .Rprofile
        git commit -m "renv"
        git lfs push origin HEAD # first push LFS, otherwise failure because of lfs.url
        git push origin HEAD

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
